# Generated by Django 4.0.4 on 2022-06-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importexcel',
            name='fexcel',
            field=models.FileField(unique=True, upload_to='excel/%Y/%m/%d'),
        ),
    ]
